name: condynsate
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.16
  - aiosignal=1.3.2
  - alabaster=1.0.0
  - anyio=4.9.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - astroid=3.3.9
  - asttokens=3.0.0
  - async-lru=2.0.5
  - asyncssh=2.20.0
  - atomicwrites=1.4.1
  - attrs=25.3.0
  - autopep8=2.0.4
  - babel=2.17.0
  - backports=1.0
  - backports.tarfile=1.2.0
  - beautifulsoup4=4.13.4
  - binaryornot=0.4.4
  - black=25.1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.2
  - cookiecutter=2.6.0
  - cpython=3.12.10
  - cryptography=44.0.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - diff-match-patch=20241021
  - dill=0.4.0
  - docstring-to-markdown=0.16
  - docutils=0.21.2
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - flake8=7.1.2
  - fqdn=1.5.1
  - frozenlist=1.5.0
  - fzf=0.61.1
  - git=2.49.0
  - glib=2.84.1
  - glib-tools=2.84.1
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - h11=0.14.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagesize=1.4.1
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - inflection=0.5.1
  - intervaltree=3.1.0
  - ipykernel=6.29.5
  - ipython=8.35.0
  - isoduration=20.11.0
  - isort=6.0.1
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.1
  - jaraco.functools=4.1.0
  - jedi=0.19.2
  - jellyfish=1.1.3
  - jinja2=3.1.6
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - keyring=25.6.0
  - krb5=1.21.3
  - libclang13=20.1.3
  - libexpat=2.7.0
  - libffi=3.4.6
  - libglib=2.84.1
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - liblzma=5.8.1
  - libogg=1.3.5
  - libpng=1.6.47
  - libsodium=1.0.20
  - libspatialindex=2.1.0
  - libsqlite=3.49.1
  - libvorbis=1.3.7
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libzlib=1.3.1
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mistune=3.1.3
  - more-itertools=10.6.0
  - multidict=6.3.2
  - mypy_extensions=1.0.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.4.0
  - notebook-shim=0.2.4
  - numpydoc=1.8.0
  - openssl=3.5.0
  - overrides=7.7.0
  - packaging=24.2
  - pandoc=3.6.4
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pathspec=0.12.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - ply=3.11
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycodestyle=2.12.1
  - pyconify=0.2.1
  - pycparser=2.22
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygithub=2.6.1
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pylint=3.3.6
  - pylint-venv=3.0.4
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyopenssl=25.0.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - python=3.12.10
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-gssapi=1.9.0
  - python-json-logger=2.0.7
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.12.2
  - python-lsp-server-base=1.12.2
  - python-slugify=8.0.4
  - python_abi=3.12
  - pytoolconfig=1.2.5
  - pytz=2025.2
  - pyuca=1.2
  - pywin32=307
  - pywin32-ctypes=0.2.3
  - pywinpty=2.0.15
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - qdarkstyle=3.2.3
  - qstylizer=0.2.4
  - qt-main=5.15.15
  - qt-webengine=5.15.15
  - qtawesome=1.4.0
  - qtconsole=5.6.1
  - qtconsole-base=5.6.1
  - qtpy=2.4.3
  - referencing=0.36.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=14.0.0
  - roman-numerals-py=3.1.0
  - rope=1.13.0
  - rpds-py=0.24.0
  - rtree=1.4.0
  - send2trash=1.8.3
  - setuptools=78.1.0
  - sip=6.8.6
  - six=1.17.0
  - sniffio=1.3.1
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=8.2.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - spyder=6.0.5
  - spyder-base=6.0.5
  - spyder-kernels=3.0.3
  - stack_data=0.6.3
  - superqt=0.7.3
  - tabulate=0.9.0
  - terminado=0.18.1
  - text-unidecode=1.3
  - textdistance=4.6.3
  - three-merge=0.1.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tomlkit=0.13.2
  - tornado=6.4.2
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - typing_utils=0.1.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - ujson=5.10.0
  - uri-template=1.3.0
  - urllib3=2.4.0
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - watchdog=6.0.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - whatthepatch=1.0.7
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.17.2
  - yaml=0.2.5
  - yapf=0.43.0
  - yarl=1.18.3
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.7
