{% set name = "condynsate" %}
{% set version = "0.6.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/condynsate-{{ version }}.tar.gz
  sha256: ec58adae33ecd093f4b054ffdfaa696240c9880d9cb52ed2a6380b06e2c4b6c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >=3.8
    - wheel
    - matplotlib
    - meshcat-python
    - notebook
    - numpy
    - pybullet
    - pynput
    - sympy
    - scipy
    - pyside6

test:
  imports:
    - condynsate
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Simulates and visualizes articulated systems in real time
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
